[package]
name = "invert_colors"
version = "0.1.0"
edition = "2021"

[lib]
name = "invert_colors"
path = "src/invert_colors.rs"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
